### ISSUE TITLE
Graph valued random variables

### ISSUE THREAD

**Issue by kristinmg** [Statistical-Connectomics-Sp15/intro#48]
Does graph valued random variable mean that it is just one possible graph out of a set of graphs? Are the number of nodes and edges fixed?

**Comment by imichaelnorris** [comment]
1. Yes, a graph valued random variable is one posible graph out of a set of graphs.  Just like "normal" valued random variables are one number out of a range of numbers, there is a set of possible graphs and the random variable will be one of these graphs or it will represent a "distribution" on the graphs.

2. I assume that depends on how you define the graph valued random variable.  I recall our professor saying that we will always be dealing with the number of nodes being fixed in this class, so we could either define the graph-valued random variable as taking on any graph with N nodes and E edges, or we could define it as taking any graph with N nodes, which could have from 0 to n(n-1)/2 edges.

Further, we could define a distribution on the number of edges.  So maybe a graph with N nodes and 1 total edge is just as likely as a graph with N edges.  This would be a uniform distribution.  But we could also have  Gaussian distribution centered on some N that is close to a model that we would like to represent.

Or we could define a distribution on the degree of each node, which would mean that every node's degree will be a random variable according to a statistical distribution.  (I think in this case, given a large enough amount of nodes whose degree follows any distribution, we can apply the Central Limit Theorem to show that the

**Comment by kristinmg** [comment]
Thank you!

**Comment by jovo** [comment]
that's not exactly right.
remind me in the beginning of class tomorrow, and I will try to clarify...

On Wednesday, February 4, 2015, Greg Kiar <notifications@github.com> wrote:

>  Closed #48
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/48>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Statistical-Connectomics-Sp15/intro/issues/48#event-230222515>
> .
>


-- 
the glass is all full:  half water, half air.
openconnecto.me, we're hiring!
<https://docs.google.com/document/d/14SApYAzxF0Ddqg2ZCEwjmz3ht2TDhDmxyZI2ZP82_0U/edit?usp=sharing>
, jovo.me, my calendar
<https://www.google.com/calendar/embed?src=joshuav%40gmail.com&ctz=America/New_York>
