### ISSUE TITLE
Discovering Edge Dependence?

### ISSUE THREAD

**Issue by indivaux** [Statistical-Connectomics-Sp15/intro#59]
So far we've been assuming that the probability of an edge connecting any two given nodes is independent from its brethren, but in the real brain there are things like neurotrophins that influence nearby axons to form connections with certain targets or not, which shows that they're not entirely independent. What methods could be used to extract these dependences from a connectome?

**Comment by itsthefedora** [comment]
So, if you have a bunch of realizations of a graph random variable with fixed labeled nodes, you could build a edge-by-edge matrix Qij, showing the conditional probability of edge i being present given that edge j is present (and hence, trivially, Qii = 1). Independence of edge probabilities would imply that this matrix should be constant along rows (Pr{i | j} = Pr{i}). You could also do something like a KL divergence between these conditional distributions to see how "similar" edges tend to be to one another.

**Comment by kurtosis312** [comment]
In the stochastic blockmodel, the presence of edges between two pairs of vertices are not independent! However, they are conditionally independent given the block assignment function (or at minimum the blocks to which the vertices belong). So that if you fit a stochastic blockmodel to the connectome, maybe a block could correspond to such a dependency?

**Comment by gkiar** [comment]
+1 @kurtosis312
